version: '3.0'

services:
  anatimer:
    image: centos/systemd
    privileged: true
    volumes:
      - '.:/app'
      - './scripts:/usr/local/bin'
      - './systemd:/usr/local/lib/systemd/system'
